// Devtools 1.6 enables stricter complexity, size, inline-style, and security rules.
// These exact-path entries isolate debt that predates the Expo 3 migration; new
// migration files and rules remain under the managed defaults.
export default [
  {
    files: [
      'src/components/action-sheet/ActionSheet.tsx',
      'src/components/action-sheet/ActionSheetItem.tsx',
      'src/components/button/Button.tsx',
      'src/components/checkbox/Checkbox.tsx',
      'src/components/drawer/Drawer.tsx',
      'src/components/menu/Menu.tsx',
      'src/components/modal/Modal.tsx',
      'src/components/navigation/NavigationItem.tsx',
      'src/components/navigation/TabBarItem.tsx',
      'src/components/navigation/helpers.test.ts',
      'src/components/navigation/policy.test.ts',
      'src/components/radio/Radio.tsx',
      'src/components/switch/Switch.tsx',
      'src/components/tabs/Tab.tsx',
      'src/components/tabs/Tabs.tsx',
      'src/components/text-input/TextInput.tsx',
      'src/components/toast/ToastProvider.tsx',
      'src/components/tooltip/Tooltip.tsx',
      'src/internal/focus/useFocusManager.ts',
      'src/internal/overlay/OverlayProvider.tsx',
      'src/internal/resolvers/resolveInteractiveColors.ts',
      'src/internal/resolvers/resolveSelectionControlColors.ts',
      'src/layout/Grid.tsx',
      'src/layout/ScrollArea.tsx',
      'src/layout/helpers.ts',
      'src/primitives/button-base/ButtonBase.tsx',
      'src/theme/colorEngine.test.ts',
      'src/theme/colorEngine.ts',
      'src/utils/deepMerge.test.ts',
    ],
    rules: {
      'max-lines-per-function': 'off',
    },
  },
  {
    files: [
      'src/components/action-sheet/ActionSheet.tsx',
      'src/components/menu/Menu.tsx',
      'src/components/text-input/TextInput.tsx',
      'src/components/tooltip/Tooltip.tsx',
      'src/internal/resolvers/resolveSelectionControlColors.ts',
      'src/utils/deepEqual.ts',
    ],
    rules: {
      complexity: 'off',
    },
  },
  {
    files: [
      'src/components/action-sheet/ActionSheet.tsx',
      'src/components/action-sheet/ActionSheetItem.tsx',
      'src/components/badge/Badge.tsx',
      'src/components/button/Button.tsx',
      'src/components/card/Card.tsx',
      'src/components/checkbox/Checkbox.tsx',
      'src/components/drawer/Drawer.tsx',
      'src/components/icon-button/IconButton.tsx',
      'src/components/list-item/ListItem.tsx',
      'src/components/menu/Menu.tsx',
      'src/components/modal/Modal.tsx',
      'src/components/navigation/NavigationItem.tsx',
      'src/components/navigation/TabBar.tsx',
      'src/components/navigation/TabBarItem.tsx',
      'src/components/radio/Radio.tsx',
      'src/components/switch/Switch.tsx',
      'src/components/tabs/Tab.tsx',
      'src/components/tabs/TabList.tsx',
      'src/components/text-input/TextInput.tsx',
      'src/components/textarea/Textarea.tsx',
      'src/components/toast/Toast.tsx',
      'src/components/toast/ToastProvider.tsx',
      'src/components/tooltip/Tooltip.tsx',
      'src/internal/focus/FocusScope.tsx',
      'src/layout/AppBar.tsx',
      'src/layout/Center.tsx',
      'src/layout/Container.tsx',
      'src/layout/Grid.tsx',
      'src/layout/Template.tsx',
    ],
    rules: {
      'react-native/no-inline-styles': 'off',
    },
  },
  {
    files: [
      'src/components/menu/Menu.tsx',
      'src/components/menu/navigation.ts',
      'src/components/navigation/policy.test.ts',
      'src/components/tabs/navigation.ts',
      'src/core/responsive/getBreakpointFromWidth.ts',
      'src/core/responsive/resolve.ts',
      'src/internal/focus/useFocusManager.ts',
      'src/internal/resolvers/resolveOverlayZIndex.ts',
      'src/internal/resolvers/resolveTextStyles.ts',
      'src/layout/Template.tsx',
      'src/layout/helpers.ts',
      'src/theme/colorEngine.test.ts',
      'src/theme/createTheme.ts',
      'src/theme/resolveWeightTokenOverrides.ts',
      'src/utils/deepEqual.ts',
      'src/utils/deepMerge.ts',
    ],
    rules: {
      'security/detect-object-injection': 'off',
    },
  },
  {
    files: ['src/theme/ThemeContext.tsx'],
    rules: {
      // Existing Studio live-config synchronization is intentional. The React
      // Compiler healthcheck compiles this component without an opt-out.
      'react-hooks/set-state-in-effect': 'off',
    },
  },
];
