sequenceDiagram
  participant participant_Accordion as Accordion
  participant participant_normalizeAccordionValues as normalizeAccordionValues
  participant_Accordion->>participant_normalizeAccordionValues: normalizeAccordionValues()
  participant_normalizeAccordionValues-->>participant_Accordion: return
