sequenceDiagram
  participant participant_ActionSheet as ActionSheet
  participant participant_resolveOverlayAnimation as resolveOverlayAnimation
  participant participant_useContext as useContext
  participant participant_useTheme as useTheme
  participant_ActionSheet->>participant_useTheme: useTheme()
  participant_useTheme->>participant_useContext: useContext()
  participant_useContext-->>participant_useTheme: return
  participant_useTheme-->>participant_ActionSheet: return
  participant_ActionSheet->>participant_resolveOverlayAnimation: resolveOverlayAnimation()
  participant_resolveOverlayAnimation-->>participant_ActionSheet: return
