sequenceDiagram
  participant participant_Card as Card
  participant participant_useContext as useContext
  participant participant_useTheme as useTheme
  participant_Card->>participant_useTheme: useTheme()
  participant_useTheme->>participant_useContext: useContext()
  participant_useContext-->>participant_useTheme: return
  participant_useTheme-->>participant_Card: return
