sequenceDiagram
  participant participant_Checkbox as Checkbox
  participant participant_use as use
  participant participant_useControllableState as useControllableState
  participant participant_useTheme as useTheme
  participant_Checkbox->>participant_useTheme: useTheme()
  participant_useTheme->>participant_use: use()
  participant_use-->>participant_useTheme: return
  participant_useTheme-->>participant_Checkbox: return
  participant_Checkbox->>participant_useControllableState: useControllableState()
  participant_useControllableState-->>participant_Checkbox: return
