sequenceDiagram
  participant participant_Container as Container
  participant participant_isResponsiveRecord as isResponsiveRecord
  participant participant_resolveResponsive as resolveResponsive
  participant participant_resolveSpacing as resolveSpacing
  participant participant_useContext as useContext
  participant participant_useResponsiveRuntime as useResponsiveRuntime
  participant participant_useTheme as useTheme
  participant_Container->>participant_useTheme: useTheme()
  participant_useTheme->>participant_useContext: useContext()
  participant_useContext-->>participant_useTheme: return
  participant_useTheme-->>participant_Container: return
  participant_Container->>participant_useResponsiveRuntime: useResponsiveRuntime()
  participant_useResponsiveRuntime->>participant_useContext: useContext()
  participant_useContext-->>participant_useResponsiveRuntime: return
  participant_useResponsiveRuntime-->>participant_Container: return
  participant_Container->>participant_resolveResponsive: resolveResponsive()
  participant_resolveResponsive->>participant_isResponsiveRecord: isResponsiveRecord()
  participant_isResponsiveRecord-->>participant_resolveResponsive: return
  participant_resolveResponsive-->>participant_Container: return
  participant_Container->>participant_resolveSpacing: resolveSpacing()
  participant_resolveSpacing-->>participant_Container: return
