sequenceDiagram
  participant participant_ListItem as ListItem
  participant participant_useContext as useContext
  participant participant_useTheme as useTheme
  participant_ListItem->>participant_useTheme: useTheme()
  participant_useTheme->>participant_useContext: useContext()
  participant_useContext-->>participant_useTheme: return
  participant_useTheme-->>participant_ListItem: return
