sequenceDiagram
  participant participant_PopoverMenu as PopoverMenu
  participant participant_usePopoverMenuController as usePopoverMenuController
  participant_PopoverMenu->>participant_usePopoverMenuController: usePopoverMenuController()
  participant_usePopoverMenuController-->>participant_PopoverMenu: return
