sequenceDiagram
  participant participant_anchor as anchor
  participant participant_Popover as Popover
  participant participant_useControllableState as useControllableState
  participant_Popover->>participant_useControllableState: useControllableState()
  participant_useControllableState-->>participant_Popover: return
  participant_Popover->>participant_anchor: props.anchor()
  participant_anchor-->>participant_Popover: return
