sequenceDiagram
  participant participant_Radio as Radio
  participant participant_resolveIndicatorSize as resolveIndicatorSize
  participant participant_resolveSelectionControlNextChecked as resolveSelectionControlNextChecked
  participant participant_useContext as useContext
  participant participant_useControllableState as useControllableState
  participant participant_useTheme as useTheme
  participant_Radio->>participant_useTheme: useTheme()
  participant_useTheme->>participant_useContext: useContext()
  participant_useContext-->>participant_useTheme: return
  participant_useTheme-->>participant_Radio: return
  participant_Radio->>participant_useControllableState: useControllableState()
  participant_useControllableState-->>participant_Radio: return
  participant_Radio->>participant_resolveIndicatorSize: resolveIndicatorSize()
  participant_resolveIndicatorSize-->>participant_Radio: return
  participant_Radio->>participant_resolveSelectionControlNextChecked: resolveSelectionControlNextChecked()
  participant_resolveSelectionControlNextChecked-->>participant_Radio: return
