sequenceDiagram
  participant participant_Radio as Radio
  participant participant_use as use
  participant participant_useControllableState as useControllableState
  participant participant_useTheme as useTheme
  participant_Radio->>participant_useTheme: useTheme()
  participant_useTheme->>participant_use: use()
  participant_use-->>participant_useTheme: return
  participant_useTheme-->>participant_Radio: return
  participant_Radio->>participant_useControllableState: useControllableState()
  participant_useControllableState-->>participant_Radio: return
