sequenceDiagram
  participant participant_isResponsiveRecord as isResponsiveRecord
  participant participant_resolveResponsive as resolveResponsive
  participant_resolveResponsive->>participant_isResponsiveRecord: isResponsiveRecord()
  participant_isResponsiveRecord-->>participant_resolveResponsive: return
