sequenceDiagram
  participant participant_Tabs as Tabs
  participant participant_useControllableState as useControllableState
  participant participant_useTabsController as useTabsController
  participant_Tabs->>participant_useTabsController: useTabsController()
  participant_useTabsController->>participant_useControllableState: useControllableState()
  participant_useControllableState-->>participant_useTabsController: return
  participant_useTabsController-->>participant_Tabs: return
