sequenceDiagram
  participant participant_Tabs as Tabs
  participant participant_useControllableState as useControllableState
  participant_Tabs->>participant_useControllableState: useControllableState()
  participant_useControllableState-->>participant_Tabs: return
