sequenceDiagram
  participant participant_resolveToastStatusColor as resolveToastStatusColor
  participant participant_resolveToastStatusTextColor as resolveToastStatusTextColor
  participant participant_Toast as Toast
  participant participant_use as use
  participant participant_useTheme as useTheme
  participant_Toast->>participant_useTheme: useTheme()
  participant_useTheme->>participant_use: use()
  participant_use-->>participant_useTheme: return
  participant_useTheme-->>participant_Toast: return
  participant_Toast->>participant_resolveToastStatusColor: resolveToastStatusColor()
  participant_resolveToastStatusColor-->>participant_Toast: return
  participant_Toast->>participant_resolveToastStatusTextColor: resolveToastStatusTextColor()
  participant_resolveToastStatusTextColor-->>participant_Toast: return
