sequenceDiagram
  participant participant_resolveOverlayAnimation as resolveOverlayAnimation
  participant participant_Tooltip as Tooltip
  participant participant_useContext as useContext
  participant participant_useTheme as useTheme
  participant_Tooltip->>participant_useTheme: useTheme()
  participant_useTheme->>participant_useContext: useContext()
  participant_useContext-->>participant_useTheme: return
  participant_useTheme-->>participant_Tooltip: return
  participant_Tooltip->>participant_resolveOverlayAnimation: resolveOverlayAnimation()
  participant_resolveOverlayAnimation-->>participant_Tooltip: return
