sequenceDiagram
  participant participant_use as use
  participant participant_useFontContext as useFontContext
  participant_useFontContext->>participant_use: use()
  participant_use-->>participant_useFontContext: return
