sequenceDiagram
  participant participant_use as use
  participant participant_useTheme as useTheme
  participant participant_useThemeConfig as useThemeConfig
  participant_useThemeConfig->>participant_useTheme: useTheme()
  participant_useTheme->>participant_use: use()
  participant_use-->>participant_useTheme: return
  participant_useTheme-->>participant_useThemeConfig: return
