sequenceDiagram
  participant participant_getBreakpointFromWidth as getBreakpointFromWidth
  participant participant_useBreakpoint as useBreakpoint
  participant participant_useWindowDimensions as useWindowDimensions
  participant_useBreakpoint->>participant_useWindowDimensions: useWindowDimensions()
  participant_useWindowDimensions-->>participant_useBreakpoint: return
  participant_useBreakpoint->>participant_getBreakpointFromWidth: getBreakpointFromWidth()
  participant_getBreakpointFromWidth-->>participant_useBreakpoint: return
