sequenceDiagram
  participant participant_use as use
  participant participant_useTheme as useTheme
  participant participant_useThemeMode as useThemeMode
  participant_useThemeMode->>participant_useTheme: useTheme()
  participant_useTheme->>participant_use: use()
  participant_use-->>participant_useTheme: return
  participant_useTheme-->>participant_useThemeMode: return
