sequenceDiagram
  participant participant_useContext as useContext
  participant participant_useTranslationContext as useTranslationContext
  participant_useTranslationContext->>participant_useContext: useContext()
  participant_useContext-->>participant_useTranslationContext: return
