sequenceDiagram
  participant participant_useContext as useContext
  participant participant_useFontContext as useFontContext
  participant_useFontContext->>participant_useContext: useContext()
  participant_useContext-->>participant_useFontContext: return
