sequenceDiagram
  participant participant_use as use
  participant participant_useTranslationContext as useTranslationContext
  participant_useTranslationContext->>participant_use: use()
  participant_use-->>participant_useTranslationContext: return
