sequenceDiagram
  participant participant_use as use
  participant participant_useResponsiveRuntime as useResponsiveRuntime
  participant_useResponsiveRuntime->>participant_use: use()
  participant_use-->>participant_useResponsiveRuntime: return
