sequenceDiagram
  participant participant_useContext as useContext
  participant participant_useResponsiveRuntime as useResponsiveRuntime
  participant_useResponsiveRuntime->>participant_useContext: useContext()
  participant_useContext-->>participant_useResponsiveRuntime: return
